SE IMPORTAN LAS LIBRERIAS

In [2]:
# Librerias necesarias para el procesado de dataframes

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import csv
import itertools

# Librerias necesarias para el funcionamiento de la red

import tensorflow as tf
import keras 
from keras.models import Sequential
from keras.layers import Dense



SE IMPORTA LA MATRIZ DE ENTRENAMIENTO




In [3]:
# El archivo de datos original se encuentra en formato 'TXT', y es necesario el siguiente código para poder leerlo 
# como un csv:

df_1 = pd.read_csv('bank.txt', header = None)
df_1

0         1        2        3  4
0     3.62160   8.66610  -2.8073 -0.44699  0
1     4.54590   8.16740  -2.4586 -1.46210  0
2     3.86600  -2.63830   1.9242  0.10645  0
3     3.45660   9.52280  -4.0112 -3.59440  0
4     0.32924  -4.45520   4.5718 -0.98880  0
...       ...       ...      ...      ... ..
1367  0.40614   1.34920  -1.4501 -0.55949  1
1368 -1.38870  -4.87730   6.4774  0.34179  1
1369 -3.75030 -13.45860  17.5932 -2.77710  1
1370 -3.56370  -8.38270  12.3930 -1.28230  1
1371 -2.54190  -0.65804   2.6842  1.19520  1

[1372 rows x 5 columns]

SE PROCESA LA MATRIZ DE ENTRENAMIENTO

In [4]:
# Se sustituye el valor númerico que dan título a las columnas por su título correspondiente:

df_1.columns =(['Variance', 'Skewness', 'Kurtosis', 'Entropy', 'Class'])
df_1

Variance  Skewness  Kurtosis  Entropy  Class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [5]:
# Se comprueba que el data frame no contiene valores mal informados

print(df_1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Variance  1372 non-null   float64
 1   Skewness  1372 non-null   float64
 2   Kurtosis  1372 non-null   float64
 3   Entropy   1372 non-null   float64
 4   Class     1372 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 53.7 KB
None


In [6]:
# Se comprueba si existen registros duplicados y en caso afirmativo se eliminan

df_1_duplicated = df_1[df_1.duplicated()]
df_1_duplicated.shape

(24, 5)

In [7]:
df_1_filtered = df_1.drop_duplicates()
df_1_filtered.shape

(1348, 5)

In [8]:
#Se seleccionan las variables independientes y las dependientes:

x = df_1.iloc[:,0:4].values
y = df_1.iloc[:,4].values


In [9]:
x

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [10]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [23]:
# Se divide el dataframe en la matriz de entrenamiento y la matriz de test:


from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2, random_state=65)


In [24]:
# Número de registros de entrenamiento

print(len(x_train))

1097


In [25]:
# Número de registros de test

print(len(x_test))

275


In [26]:
# Escalado de los datos del dataframe

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x_train=sc.fit_transform(x_train)
x_test_sc=sc.fit_transform(x_test)


In [27]:
print(len(x_train))

1097


SE DEFINE LA RED NEURONAL

In [28]:
from keras.optimizers import Adadelta

red = Sequential()

    #Agregado de capa de entrada
    
red.add(Dense( units = 6, activation = 'relu', kernel_initializer='uniform'))

    #Agregado de capa oculta
    
red.add(Dense( units = 2, activation = 'relu',  kernel_initializer='uniform'))
red.add(Dense( units = 8, activation = 'relu',  kernel_initializer='uniform'))
red.add(Dense( units = 8, activation = 'relu',  kernel_initializer='uniform'))

     #Agregado de capa de salida
    
red.add(Dense( units = 1, activation = 'sigmoid',  kernel_initializer='uniform'))

    #Compilado de la red
    

opt = 'Adam'
red.compile(optimizer=opt, loss="binary_crossentropy", metrics=['accuracy'])



In [29]:
# Entrenamiento del modelo
    
red.fit(x_train, y_train, batch_size=10, epochs=(100))

Epoch 1/100
110/110 [==============================] - 0s 590us/step - loss: 0.6928 - accuracy: 0.5187
Epoch 2/100
110/110 [==============================] - 0s 627us/step - loss: 0.6689 - accuracy: 0.5387
Epoch 3/100
110/110 [==============================] - 0s 568us/step - loss: 0.4303 - accuracy: 0.7539
Epoch 4/100
110/110 [==============================] - 0s 769us/step - loss: 0.2991 - accuracy: 0.9799
Epoch 5/100
110/110 [==============================] - 0s 627us/step - loss: 0.2324 - accuracy: 0.9881
Epoch 6/100
110/110 [==============================] - 0s 627us/step - loss: 0.1804 - accuracy: 0.9927
Epoch 7/100
110/110 [==============================] - 0s 568us/step - loss: 0.1412 - accuracy: 0.9909
Epoch 8/100
110/110 [==============================] - 0s 627us/step - loss: 0.1112 - accuracy: 0.9918
Epoch 9/100
110/110 [==============================] - 0s 627us/step - loss: 0.0904 - accuracy: 0.9909
Epoch 10/100
110/110 [==============================] - 0s 568us/step - l

110/110 [==============================] - 0s 627us/step - loss: 0.0161 - accuracy: 0.9936
Epoch 80/100
110/110 [==============================] - 0s 485us/step - loss: 0.0187 - accuracy: 0.9918
Epoch 81/100
110/110 [==============================] - 0s 426us/step - loss: 0.0173 - accuracy: 0.9927
Epoch 82/100
110/110 [==============================] - 0s 627us/step - loss: 0.0177 - accuracy: 0.9927
Epoch 83/100
110/110 [==============================] - 0s 627us/step - loss: 0.0178 - accuracy: 0.9909
Epoch 84/100
110/110 [==============================] - 0s 568us/step - loss: 0.0178 - accuracy: 0.9936
Epoch 85/100
110/110 [==============================] - 0s 627us/step - loss: 0.0167 - accuracy: 0.9918
Epoch 86/100
110/110 [==============================] - 0s 627us/step - loss: 0.0181 - accuracy: 0.9918
Epoch 87/100
110/110 [==============================] - 0s 568us/step - loss: 0.0167 - accuracy: 0.9927
Epoch 88/100
110/110 [==============================] - 0s 627us/step - loss:

In [30]:
# Ejecución de la spredicciones

predict = red.predict(x_test)
predict

array([[1.38526387e-28],
       [3.86387895e-33],
       [8.67002940e-26],
       [9.98930514e-01],
       [2.77069771e-17],
       [2.31857681e-38],
       [3.92845391e-34],
       [9.98930514e-01],
       [5.39830089e-01],
       [1.30226910e-02],
       [8.61573115e-14],
       [0.00000000e+00],
       [7.41804985e-18],
       [5.90709588e-21],
       [9.98930514e-01],
       [2.65338690e-24],
       [2.07066536e-03],
       [9.98930514e-01],
       [9.98930514e-01],
       [1.95503235e-04],
       [9.05334413e-01],
       [2.00363615e-11],
       [1.20048640e-17],
       [0.00000000e+00],
       [8.61024857e-03],
       [4.16661169e-26],
       [2.50503425e-34],
       [9.98930514e-01],
       [9.76874560e-34],
       [7.45850419e-35],
       [3.66129439e-31],
       [5.12830347e-08],
       [2.90860325e-37],
       [5.49456966e-26],
       [1.20710547e-14],
       [1.99049711e-04],
       [2.66839301e-10],
       [0.00000000e+00],
       [1.11923391e-07],
       [1.89816080e-28],


In [31]:
# Para poder ejecutar la métrica y comprobar el porcentaje de acierto es necesario redondear los valores de las predicciones a la unidad para poder comparalos

predict_sc=np.round(predict)

predict_sc

array([[0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],

In [32]:
# Medición del porcentaje de acierto

from sklearn.metrics import confusion_matrix

nc = confusion_matrix(y_test,predict_sc)
nc

array([[171,   0],
       [ 43,  61]], dtype=int64)

In [33]:
(152+88)/275

0.8727272727272727

In [34]:
from sklearn.metrics import roc_auc_score

roc_auc = roc_auc_score(y_test, predict_sc)
print(roc_auc)

0.7932692307692308
